user_name = '#userName'
password = '#password'
login = '#root > div > div.content___3Paa8 > div.main___1F5GY > div > form > div:nth-child(4) > div > div > span > button'
remeber_password = '#root > div > div.content___3Paa8 > div.main___1F5GY > div > form > div:nth-child(3) > label'
forget_password = '#root > div > div.content___3Paa8 > div.main___1F5GY > div > form > div:nth-child(3) > a'
user_name = '#root > div > div > section > div.banner-cont > div.suspension > div > div > div:nth-child(2) > input[type=text]'
password = '#root > div > div > section > div.banner-cont > div.suspension > div > div > div:nth-child(3) > input[type=password]'
login = '#root > div > div > section > div.banner-cont > div.suspension > div > div > div.login-btn > a'
remeber_password = '#root > div > div > section > div.banner-cont > div.suspension > div > div.login-cont > div.login-check > label'
forget_password = '#root > div > div > section > div.banner-cont > div.suspension > div > div.login-cont > div.login-check > a'

